GrafeasGroup/buttercup

- buttercup/cogs/restrictor.py
- buttercup/strings/en_US.yaml
In this PR, the "Restrictor" cog is further updated to send a message based on whether the nickname starts with the `u/` prefix rather than `/u/`. To allow this to be done in a systematic way, the workflow has been reworked using an Observer pattern, where the restrictor keeps track of a Record for each encountered member, which triggers a set of conditional handlings when this record is updated.
{description}
> Change workflow and add wrong prefix message

- buttercup/cogs/ping.py
- buttercup/main.py
Relevant issue: Closes #25.
Adds a `/ping` command to determine if the bot is still responsive and if the server is online.
It also determines the latency of Blossom via the `/ping` endpoint.
Unfortuantely, I was unable to add the delay information for buttercup itself, as the slash command doesn't appear to provide timestamps.
> Add ping command

- buttercup/cogs/stats.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #19.
Adds a `/stats` command that displays statistics about all users of the server.
> Add stats command

- README.md
- buttercup/cogs/rules.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
- poetry.lock
- pyproject.toml
Relevant issue: Closes #31.
Adds a `/rules` command to get the rules of a given subreddit. This will be useful for moderation when someone asks if a post is allowed on a subreddit. Instead of openening Reddit and looking for the sub you can just do it in Discord.
Unfortunately this also adds praw as dependency and adds another bot token, but I think it's worth it (and we might want to add other Reddit features along the line).
> Add rules command

- README.md
- buttercup/bot.py
- buttercup/cogs/__init__.py
- buttercup/cogs/handlers.py
- buttercup/cogs/heatmap.py
- buttercup/cogs/helpers.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
- poetry.lock
- pyproject.toml
Relevant issue: Closes #29.
Adds a `/heatmap` command to display the activity heatmap of the given user.
The output looks like this:
The image can be clicked for a larger view of the heatmap.
Please note that the current data is mostly incorrect because most dates in Blossom are still wrong (see GrafeasGroup/blossom#157).
> Add `/heatmap` command

- buttercup/cogs/helpers.py
- buttercup/cogs/rules.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #36.
Adds a `/pirules` command to automatically identify rules regarding personal information.
This is accomplished by looking for specific keywords in the rule title and description.
I checked most subs with the command and it appears to be reliably detecting all PI rules.
Additionally, this improves the handling of subs with no rules or which are private, also for the `/rules` command.
> Add `/pirules` command

- buttercup/cogs/helpers.py
- buttercup/cogs/stats.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #23.
Adds a `/progress` command to display the 100/24 progress of a user.
This is one of the most often used commands of the old bot.
If 24 hours are specified as time frame (default), the bot will display a progress bar to reach 100/24. Additionally, a random motivational message for the current transcription count will be displayed.
Feel free to add more motivational messages or edit the existing ones, the more variety we have the better!
> Add `/progress` command

- buttercup/cogs/__init__.py
- buttercup/cogs/handlers.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
- poetry.lock
- pyproject.toml
Relevant issue: Closes #21.
Adds a `/history` command which creates a plot of the user's gamma over time. Multiple users can be provided to be plotted together.
Unfortunately, they are not correct yet due to the wrong dates in the Blossom API (GrafeasGroup/blossom#157).
What's missing in comparison to the old bot is that you can't specify a time frame to restrict the graph to. I am not sure yet how to integrate this properly with the Discord commands, so I want to move this to a separate issue. It's also not used that often, so we can omit it for now.
The command takes about 2.5 seconds for each provided user, which is a bit long. But it's a big improvement to the 45 seconds we had with a previous iteration. Maybe we can optimize the rate command in the API for shorter delays.
> Add `/history` command

- README.md
This makes the Buttercup image in the Readme transparent and a little bit smaller. This makes it look much better when using the dark theme, IMO.
Old:
New:
> Make Buttercup image transparent

- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #22
Adds a `/rate` command that displays the transcribing rate of up to three users.
The rate data itself is still wrong due to the placeholder transcriptions still left in Blossom.
> Add `/rate` command

- buttercup/cogs/handlers.py
- buttercup/cogs/heatmap.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
- poetry.lock
- test/test_helpers.py
Relevant issue: Closes #61
This PR adds powerful utility functions to parse user-given times. It can handle absolute times like `2021-09-14`, but also relative ones like `3` or `3 hours` for the time that was 3 hours ago.
These values are then used to filter the data that the heatmap is calculated on.
For example, the command `/heatmap user:Tim3303 from:2020-06-07 until:3` will calculate the heatmap on the submissions made by u/Tim3303 between 2020-06-07 and 3 hours ago.
This time filtering can easily be added to other commands like `/rate`, `/history` and `/progress` in future PRs.
> Add time filtering to `/heatmap` command

- buttercup/cogs/helpers.py
The code used `datetime.time.mktime` instead of `time.mktime`.
This resulted in an unresolved reference, causing the `/userstats` command to raise an error.
> Fix `/userstats` command raising error

- buttercup/cogs/heatmap.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
- test/test_helpers.py
Relevant issue Closes #62, closes #58
Merge after GrafeasGroup/blossom#203!
This PR adds time filtering to the `/rate` and `/history` commands via the `after` and `before` options.
The time can be provided by an absolute or relative time string, just like for the `/heatmap` command.
Additionally, the automatic time granularity heuristic has been updated to consider the time frame that the data is calculated on.
It now provides a lot finer granularity by default to preserve details in the graphs.
**Note**: Currently a line is drawn until the current date, independent of the filters. This will be fixed in a future PR related to #59.
> Add time filtering to `/rate` and `/history` commands

- buttercup/cogs/rules.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #70
The `/pirules` command returned the wrong message when no PI rules had been found.
It always responded that the sub didn't have any rules at all, even if it did.
Now it correctly distinguishes between no rules and no PI rules.
> Fix /pirules response for no PI rules

- buttercup/cogs/stats.py
Relevant issue: Closes #57
⚠️ Merge **after** GrafeasGroup/blossom#204! ⚠️ 
When the completed_time attribute is null it appears before the other transcriptions in the ordering.
This resulted in very old times being displayed in some cases.
Now, the submissions without complete time are filtered out, fixing the problem.
> Fix last active time if user has submissions without completed time

- buttercup/cogs/handlers.py
- buttercup/cogs/history.py
Relevant issue: Closes #73, closes #35
- Log the stack trace when an unknown exception is raised (#35)
- Fix `KeyError` for `/history` and `/rate` commands when using with multiple users
> Fix KeyError for multi-graph commands

- buttercup/cogs/history.py
Relevant issue: Closes #78.
- Labels the latest point in the `/history` graph
- Labels the maximum point in the `/rate` graph
The positioning of the labels isn't ideal yet and might be improved in future PRs.
> Add data labels to `/rate` and `/history` graphs

- buttercup/cogs/history.py
Relevant issue: #83 
Turns out that I didn't push some commits last time (my git aliases weren't configured correctly).
For this reason, only one offset calculation got fixed, the other one (missing data points) was still bugged.
This PR adds those remaining commits and also applies some refactorings to make the code more readable.
Before:
After:
> Fix history gamma offset (for real)

- buttercup/cogs/stats.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #68.
The user can specify an `after` and `before` parameter similar to the `/history` and `/rate` commands.
Both absolute and relative times are supported.
The progress bar is only shown if the time frame is approx. 24 hours long (otherwise the bar wouldn't make much sense).
> Allow arbitrary timeframes for /progress command

- buttercup/cogs/name_validator.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #84
This PR reworks the previous name validation system.
The previous approach of saving all usernames to a cache and using it to keep track of the changes was very error prone and didn't work when the bot was restarting.
The new approach is much simpler and just uses the old and new names provided by the member update event.
I also included an automatic fix if the user forgets to use the leading slash.
Response when username is valid:
Response when username is invalid:
- Only allow the `[mod]` tag in the display name for actual mods (#85)
- Check if the username exists on Blossom/Reddit (#86)
- Kick members automatically when the display name is invalid for 12 hours
- Also track username changes (from one valid display name to another, but the username changed)
> Rework name validation

- buttercup/cogs/leaderboard.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #18.
This PR adds an implementation of a `/leaderboard` command, which displays a leader-board of the volunteers, sorted by their gamma.
This will replace the `!leaderboard` command of ToR-Stats.
Improvements compared to the previous version:
- Embed colored in the user's rank.
- Users can define the time-frame that the leader-board is calculated on. E.g., they can display the leader-board of last week only.
> Add `/leaderboard` command

- buttercup/cogs/welcome.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #82.
The bot will send a welcome message with instructions on how to change the display name whenever a new member joins.
> Send welcome message when new user joins

- .flake8
- buttercup/cogs/find.py
- buttercup/cogs/search.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
- test/test_search.py
Relevant issue: Closes #96.
This implements a `/search` command to search for a transcription by a phrase from the transcription text (case-insensitive).
This functionality is available in ToR-Stats via the `!where` command.
In comparison to the old implementation, I made the following improvements:
- Automatic recognition of post type and subreddit (this makes it easier to find the right transcription at a glance).
- Preview of up to four occurrences of the words.
- Line numbers and underline for the occurrences.
- Fixed pagination. Only 5 results are displayed at a time. The user can go through all results by using the provided reaction emojis. On the API side, 25 transcriptions are fetched, so only every 5th page needs to make a new request. (Pagination is currently broken in …
> Add `/search` command

- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #90.
This PR adds the option to provide a username as `goal` for the `/until` command.
The bot will then calculate when the user will "catch up" with the goal user, i.e., the intersection points of their gamma considering the rate of the past week.
> Add option to use users as goal for `/until` command

- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #104.
- Fixes a `KeyError` when formatting the output of `/until` when the user hasn't transcribed anything recently.
- Fixes the output of `/until` when the user has already reached the goal.
The bot now gives a different message when the goal has already been reached:
> Fix key error for until command, fix output when goal is reached

- buttercup/cogs/history.py
Relevant issue: Closes #59.
The user can restrict the time frame that is considered when creating a `/history` graph.
The bot now does a much better job at the following:
- Filling in straight lines if the user didn't transcribe at the start or end of the time frame.
- "Zooming in" on the top part if the gamma doesn't start at zero. This provides a lot more detail for high-ranked users.
- The highest shown milestone/rank line is now calculated based on the highest point in the graph instead of the users total gamma.
Before:
After:
> Adjust zoom for history graphs

- buttercup/cogs/history.py
This is a hotfix for a Buttercup error, which occurred because a localized and an unlocalized timezone were used together in an equation.
I'm not sure if this will actually fix the bug, because I wasn't able to reproduce the issue locally.
Original error:
```
Dec 10 18:45:04 localhost python[19811]: TypeError: Timestamp subtraction must have the same timezones or no timezones
Dec 10 18:45:04 localhost python[19811]: 2021-12-10 18:45:04,160 | WARNING | [aeb28572-6b04-407b-9df7-50b8e193519a] TypeError: Timestamp subtraction must have the same timezones or no timezones
Dec 10 18:45:04 localhost python[19811]: Traceback (most recent call last):
Dec 10 18:45:04 localhost python[19811]:   File "/data/buttercup/.venv/lib/python3.9/site-packages/discord_slash/client.py", line …
```
> Hotfix: Fix misconfigured timezones for rate calculation

- buttercup/cogs/helpers.py
- buttercup/cogs/search.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #106.
This adds options to the `/search` command that allow to restrict the results to a specific user and time frame. The user executing the command will be the default user.
> Add options for user and time filtering for `/search` command

- buttercup/cogs/handlers.py
- buttercup/cogs/heatmap.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/cogs/leaderboard.py
- buttercup/cogs/search.py
- buttercup/cogs/stats.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #112.
This is a major rework to simplify the process of validating usernames and getting the user data from Blossom.
This has several advantages:
- Consistency across all commands.
- Reduced code duplication, better error handling.
- We get some new features for "free", because we can always handle keywords like `me` and `all` for the username.
The `/heatmap`, `/leaderboard` and `/progress` commands can now also take the `all` keyword to show the stats for the whole ToR community. 
After merging this, all commands should be tested extensively to ensure that no formatting key errors or other bugs have sneaked in.
> Rework username handling

- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- test/test_helpers.py
Relevant issue: Closes #101.
In some circumstances, usernames containing Reddit formatting, such as `__TestUser__` would not render properly in the bot responses. This PR properly escapes the usernames to fix that.
> Escape Discord formatting in usernames

- buttercup/cogs/history.py
Relevant issue: Closes #116
This enables the use of keywords like `all` for the username of the `/history` and `/rate` commands to get the stats for all users.
It's not perfect yet, because of some submissions without a proper date, the rate graph has a huge spike at some point.
Also the data granularity should be chosen properly to reduce losing times.
> Add option to use history and rate with all users

- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #93
This adds the option to define the time frame that is used to calculate the predictions for the `/until` command.
It also adds a bunch of smaller features:
- You can make predictions for the whole server using keywords like `all`.
- Added thousand separators for all gamma values.
- Added absolute time of the prediction (localized via Discord).
> Add option to provide time frame to `/until` command

- buttercup/cogs/search.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #119
This adds localized, relative timestamps to the results of the `/search` command. 
This should make it easier to identify the exact post that you are looking for.
Additionally, the way that the query occurrences are displayed has been improved.
It now shows as much "context" to the occurrence as possible on both sides, while still fitting in a single line (on a Desktop embed).
Before, it would sometimes wrap into the next line if the query string was long, or the result was truncated when there was still room left.
> Add timestamps to `/search` results

- buttercup/cogs/heatmap.py
- buttercup/cogs/history.py
- buttercup/cogs/leaderboard.py
- buttercup/cogs/stats.py
Relevant issue: GrafeasGroup/blossom#228
This replaces the 'from' query parameter with 'complete_time__gte' as well as 'until' with 'complete_time__lte'.
Directly depends on GrafeasGroup/blossom#228, which needs to be merged and deployed first.
While the new system is deployed and this PR not merged, most Buttercup commands won't work with time filters.
**Note:** This needs to be tested with the new deployed time filters before merging!
All commands need to be tested with time filters. It needs to be ensured that the commands don't throw any new errors and that the correct time frames are filtered.
This should be tested with both absolute and relative commands.
> Replace submission time filters with new version

- buttercup/cogs/search.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #123
The new username helper functions weren't applied everywhere in the search command, resulting in the 'me' keyword not working correctly.
> Rework search command with new username helper functions

- buttercup/cogs/history.py
Relevant issue: Closes #79
This improves the color selection for the graph lines of `/rate` and `/history`. It will now prefer a user's rank color, making it easier to recognize each user at a glance.
Users are now also sorted by their gamma for the graph commands.
> Improve `/rate` and `/history` color selection

- buttercup/strings/en_US.yaml
Relevant issue: Closes #125
Due to the changes of the way usernames are handled, the progress messages included a duplicate u/ prefix.
This issue has now been resolved by removing the prefix from the localization files.
> Fix username placeholders in `/progress` command

- buttercup/cogs/stats.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #126
This adds the current leaderboard rank of the user to the output of the `/stats` command.
> Add leaderboard rank to `/stats` command

- buttercup/cogs/search.py
Relevant issue: Closes #131
When used in a DM, the `/search` command failed with an error.
This is because the bot doesn't have permission to clear the reactions of a message in a DM.
Instead, the bot now falls back to removing its own reactions one by one.
This is less efficient and results in the controls not being ordered (because the option selected by the user gets stuck), but I think this is the only way to implement this.
> Fix /search command not working in DMs

- README.md
- buttercup/bot.py
- buttercup/cogs/admin.py
- buttercup/cogs/config.py
- buttercup/cogs/handlers.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #133
This reworks how the permissions for admin commands are handled.
Before, the permissions would be checked on command execution. When the user didn't have a specified role, the command would return an error message and log the incident.
Now, we are using the built-in permission system of slash commands. When a user doesn't have the required role in the guild, the admin commands will be grayed out and the user won't be able to execute them.
The implementation is a bit hacky, because the permissions are defined in annotations and we can't directly access the config from there. So now we define a global variable in a cog that we load first and then use that to generate the permissions.
This allows us to define the permissions in the config without hard-coding them …
> Rework admin command permissions

- buttercup/cogs/history.py
This fixes a bug that resulted the `/rate` and `/history` commands in throwing an error when running them for all users.
The bot was trying to sort the users by gamma, but the users are `None` when running for everyone.
> Fix rate and history command throwing error when running for all users

- buttercup/cogs/handlers.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/cogs/stats.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #139
When a user has zero gamma, but is in our database, it breaks most commands.
So instead we now throw a custom error when fetching the user and handle that at a central place.
> Respond with custom message when user has 0 gamma

- buttercup/cogs/leaderboard.py
Relevant issue: Closes #141 
The datetime that is used to calculate the duration of the leaderboard time when no after time was provided was timezone naive.
This resulted in a timezone error when the duration was calculated and made the command fail.
It now has UTC added to avoid this problem.
> Fix error when executing `/leaderboard` without after but with before time

- README.md
- buttercup/cogs/name_validator.py
Relevant issue: Closes #146
The `valid_role_id` in the config is now named `verified_role_id`.
If the role id is not provided, the bot will now log a warning instead of throwing an error.
Note that this doesn't require changes in the prod config, as we already (incorrectly) user the `verified_role_id` name.
This PR should therefore fix the bot not posting a welcome message.
> Rename valid role to verified role

- buttercup/cogs/find.py
Relevant issue: Closes #148
We had the problem that the `/find` command previews images, even if they are NSFW. Volunteers don't have the ability to remove the bot's previews, so if they accidentally searched for something NSFW it was stuck in the chat.
Unfortunately, it's not possible to spoiler the preview images in embeds.
Instead, we now don't include the image and transcription preview if the post is marked NSFW.
The post links will now also include a note that the post is NSFW.
Additionally, this PR adds the post title to the `/find` response. If the post is NSFW, it will be spoilered.
Note that this all depends on the post being marked as NSFW in Blossom, not on Reddit.
So this will benefit from GrafeasGroup/blossom#263 being implemented.
> Don't preview NSFW content

- buttercup/cogs/history.py
Relevant issue: Closes #153
Even if the time frame for the /rate graph was restricted, it would include a point for the current date.
This resulted in restricted time frames being squished and a long flat line to fill in the rest.
Before:
After:
> Fix rate graph always including a point for the current date

- buttercup/cogs/heatmap.py
Relevant issue: Closes #151
The pyplot figures to create the heatmap weren't closed properly after use.
This resulted in them cluttering up the memory.
> Properly close heatmap figure after use

- buttercup/cogs/helpers.py
- buttercup/cogs/name_validator.py
- test/test_helpers.py
Relevant issue: Closes #155
The name change confirmation message would cut off the last character of the username, if the user didn't include their timezone in the nickname.
This PR merges the username regex from the name validator and helper functions and fixes this bug along the way. I also added more tests to verify that it works correctly.
> Fix name change confirmation message

- buttercup/cogs/history.py
Relevant issue: Closes #156
By default, the /until command takes the next rank as goal.
However, if the maximum rank has already been reached, it would throw an error.
Now, it will fall back to the next 10,000 tier.
> Fix `/until` crashing if the max rank has already been reached

- buttercup/cogs/heatmap.py
- buttercup/cogs/helpers.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
- test/test_helpers.py
Relevant issue: Closes #145
This PR includes several improvements to how timezone localization is handled:
- Timezones can now include a minute fraction (e.g. `UTC+10.5` or `UTC-05:30`)
- Timezone localization is now handled by the server instead of Buttercup itself
- Added timezone localization to `/rate` and `/history` graphs
Currently the timezone of the user executing the command is used for all command executions.
If you execute the command for another user, it will still use your timezone.
In the future, we should cache the timezone of a user if they execute a command or change their nickname and then use the target's timezone instead of your own timezone.
Additionally, we could add an optional command parameter to specify a custom timezone.
> Improve timezone handling

- buttercup/cogs/search.py
Relevant issue: Closes #163
While implementing an optimization I accidentally broke the pagination.
Instead of caching only responses with multiple pages, it cached only responses with a single page.
Thus, when reacting, the message was never in the cache.
> Fix pagination not working for `/search` results

- buttercup/cogs/helpers.py
- buttercup/cogs/queue.py
- buttercup/cogs/search.py
- buttercup/main.py
- buttercup/strings/en_US.yaml
- test/test_helpers.py
- test/test_search.py
Relevant issue: Closes #42.
This adds a `/queue` command to display the current status of the queue.
**Features**:
- Showing the number of unclaimed posts (see Future Work for limitations), as well as the number of posts per subreddit.
- Showing the number of claimed posts (last 48 hours), as well as the 5 most recent claims.
- The last 5 messages will be updated automatically every couple of minutes.
- Synchronize the removed posts with Reddit (on Blossom). Right now, the number of unclaimed posts will be higher than on the subreddit, because we don't know which posts have been removed. This will also be important for the app.
- Recognize if a message has been pinned. Right now, only the last 5 messages are updated for performance reasons. Therefore, we cannot pin the queue message, …
> Add `/queue` command

- buttercup/cogs/queue.py
Quick PR to not count removed posts in the `/queue` command.
> Don't count removed posts in the queue

- buttercup/cogs/queue.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #171
This adds the 5 most recently completed transcriptions to the `/queue` message.
I think we'll have to optimize our API to make the updates faster, but the info is definitely nice to have.
> Add recently completed transcriptions to `/queue` message

- buttercup/cogs/queue.py
Relevant issue: Closes #177
If the unclaimed, claimed or completed posts records are empty, the pandas frames did not have any columns set.
This resulted in the updater crashing and the queue not updating anymore.
We now explicitly set the columns to prevent this.
> Fix update loop crashing with empty records

- buttercup/strings/en_US.yaml
This typo has lived rent-free in my head ever since I first saw it. I just wanna get rid of it.
> Transcribing, not transribing

- buttercup/cogs/history.py
Relevant issue: None
This fixes an error when executing the history and rate commands, because of an argument name mismatch.
Those were changed on the Discord side at some point, but not adjusted in the code.
Additionally, a deprecated Pandas command has been changed.
Notably the legend for multiple users seems to be bugged, showing a dot in the first color for the second user. I have no idea why and will move this to a different issue:
> Fix arguments of rate and history commands

- buttercup/cogs/heatmap.py
- buttercup/cogs/history.py
- buttercup/strings/en_US.yaml
Relevant issue: Closes #184.
This PR adds a new `/activity` command which displays a map showing the user's activity in the past year. 
Contrary to the `/heatmap` command, no data is being aggregated, only the activity in the one year time frame is being displayed. This allows us to see trends of activity throughout the year.
> Add `/activity` command

- .github/workflows/build_and_test.yml
- .github/workflows/tests.yml
- buttercup/main.py
- poetry.lock
- pyproject.toml
When running poetry2setup, the `pytest` package wasn't getting picked up as a required package because it was listed as a CI-specific optional dependency. This PR fixes the dependency and cleans up the other GitHub Actions files.
> update dependencies to resolve correctly
